# Generated by Django 4.2.7 on 2023-12-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_video_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
